openapi: 3.0.1
info:
  title: GetCustomerWaselNotCancelled
  description: API Definition of GetCustomerWaselNotCancelled
  version: 1.0.0
servers:
- url: http://localhost:8290/GetCustomerWaselNotCancelled
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
