openapi: 3.0.1
info:
  title: ProcessAPICustomerWasel
  description: API Definition of ProcessAPICustomerWasel
  version: 1.0.0
servers:
- url: http://localhost:8290/ProcessAPICustomerWasel
paths:
  /:
    get:
      responses:
        default:
          description: Default response
