openapi: 3.0.1
info:
  title: VerifyandRegisterProcessAPI
  description: API Definition of VerifyandRegisterProcessAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/VerifyandRegisterProcessAPI
paths:
  /:
    get:
      responses:
        default:
          description: Default response
