openapi: 3.0.1
info:
  title: VerifyandRegisterCustomer
  description: API Definition of VerifyandRegisterCustomer
  version: 1.0.0
servers:
- url: http://localhost:8290/VerifyandRegisterCustomer
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
